# Generated by Django 3.1.4 on 2020-12-23 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО клиента')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес проживания')),
            ],
        ),
        migrations.CreateModel(
            name='DateContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата контактирования')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО сотрудника')),
                ('position', models.CharField(max_length=100, verbose_name='Должность сотрудника')),
                ('client', models.ManyToManyField(through='api.DateContact', to='api.Client')),
            ],
        ),
        migrations.AddField(
            model_name='datecontact',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='api.employee'),
        ),
    ]
